---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp Ransomware Resilience 문서
    url: "/index.html"
  - title: 릴리스 노트
    entries:
    - title: 랜섬웨어 복원력의 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/rp-reference-limitations.html"
  - title: 시작하기
    entries:
    - title: 랜섬웨어 복원력에 대해 알아보세요
      url: "/concept-ransomware-resilience.html"
    - title: 필수 조건
      url: "/rp-start-prerequisites.html"
    - title: 빠른 시작
      url: "/rp-start-quick-start.html"
    - title: 랜섬웨어 복원력 설정
      url: "/rp-start-setup.html"
    - title: 라이센스 설정
      url: "/rp-start-licenses.html"
    - title: 워크로드 검색
      url: "/rp-start-discover.html"
  - title: 랜섬웨어 복원력 활용
    entries:
    - title: 랜섬웨어 복원력에 액세스
      url: "/rp-start-login.html"
    - title: 워크로드 상태 보기
      url: "/rp-use-dashboard.html"
    - title: 보호 및 감지
      entries:
      - title: 보호 검토
        url: "/task-review-protection.html"
      - title: 백업 대상 구성
        url: "/task-backup-destination.html"
      - title: 작업 부하 보호
        url: "/rp-use-protect.html"
      - title: 사용자 활동 감지 구성
        entries:
        - title: 사용자 활동 감지에 대해 알아보십시오
          url: "/concept-user-behavior.html"
        - title: 사용자 활동 감지 요구 사항
          url: "/reference-user-activity-requirements.html"
        - title: 에이전트 및 수집기 구성
          url: "/suspicious-user-activity.html"
      - title: 보호 그룹 관리
        url: "/task-protection-group.html"
      - title: 개인 식별 데이터를 스캔하세요
        url: "/task-classify.html"
    - title: 대응 및 복구
      entries:
      - title: 감지된 경고에 대응
        url: "/rp-use-alert.html"
      - title: 복구 상태 검토
        url: "/rp-use-recover.html"
      - title: 사용자 지정 복원을 사용하여 복구
        url: "/rp-use-recover.html"
      - title: 클린 복원 수행
        entries:
        - title: 격리된 복구 환경 생성
          url: "/task-clean-restore.html"
        - title: 클린 복원으로 복구
          url: "/task-clean-restore-recover.html"
    - title: 준비 태세 훈련 실시
      url: "/rp-start-simulate.html"
    - title: SIEM 구성
      url: "/task-siem.html"
    - title: SOAR 플레이북 통합
      url: "/reference-soar.html"
    - title: 보고서 다운로드
      url: "/rp-use-reports.html"
  - section: support
  - title: 자주 묻는 질문
    url: "/rp-start-faq.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
