---
sidebar: sidebar 
permalink: reference-user-activity-requirements.html 
keywords: data breach detection, data breach, user activity, suspicious, anomalous, requirements, end points, operating systems, networking 
summary: 사용자 활동 에이전트 및 기타 수집기를 생성하기 전에 명시된 운영 체제, 서버 및 네트워크 요구 사항을 충족하는지 확인해야 합니다. 
---
= NetApp Ransomware Resilience를 위한 사용자 활동 감지 요구 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience 사용자 행동 감지 기능을 사용하면 사용자 수준의 랜섬웨어 이벤트에 대응할 수 있습니다. 사용자 행동 감지를 활성화하려면 에이전트 세트를 생성해야 합니다. 감지를 활성화하기 전에 Ransomware Resilience가 이벤트를 제대로 감지하고 보고할 수 있도록 명시된 운영 체제, 서버 및 네트워크 요구 사항을 충족하는지 확인해야 합니다.

온프레미스 ONTAP 시스템 및 Amazon FSx for NetApp ONTAP 및 Cloud Volumes ONTAP 시스템의 워크로드에 대해 랜섬웨어 복원력에서 사용자 행동 감지가 지원됩니다(<<클라우드 공급자 지원>>와 일치하는 시스템).



== 클라우드 공급자 지원

사용자 행동 데이터는 AWS 및 Azure의 다음 지역에 저장할 수 있습니다.

|===
| 클라우드 제공업체 | 지역 


| AWS  a| 
* 아시아 태평양(시드니)(ap-southeast-2)
* 유럽(프랑크푸르트)(eu-central-1)
* 미국 동부(버지니아 북부)(us-east-1)




| 하늘빛 | 미국 동부 
|===


== 운영 체제 요구 사항

의심스러운 사용자 행동 감지는 다음 운영 체제에서 지원됩니다.

[cols="2"]
|===
| 운영 체제 | 지원되는 버전 


| 알마리눅스 | 9.4(64비트) ~ 9.5(64비트) 및 10(64비트), SELinux 포함 


| 센트OS | CentOS Stream 9(64비트) 


| 데비안 | 11(64비트), 12(64비트), SELinux 포함 


| 오픈수세 리프 | 15.3(64비트) ~ 15.6(64비트) 


| 오라클 리눅스 | 8.10(64비트) 및 9.1(64비트) ~ 9.6(64비트), SELinux 포함 


| 레드햇 | 8.10(64비트), 9.1(64비트) ~ 9.6(64비트), 10(64비트), SELinux 포함 


| 불안정한 | SELinux를 포함한 Rocky 9.4(64비트)부터 9.6(64비트)까지 


| 수세 엔터프라이즈 리눅스 | 15 SP4(64비트)부터 15 SP6(64비트), SELinux 포함 


| 우분투 | 20.04 LTS(64비트), 22.04 LTS(64비트) 및 24.04 LTS(64비트) 
|===

NOTE: 사용자 활동 에이전트에 사용하는 컴퓨터는 다른 응용 프로그램 수준 소프트웨어를 실행하지 않아야 합니다. 전용 서버를 권장합니다.

그만큼 `unzip` 설치를 위해서는 명령어가 필요합니다. 그만큼 `sudo su -` 설치, 스크립트 실행 및 제거에는 명령어가 필요합니다.



== 서버 요구 사항

서버는 다음과 같은 최소 요구 사항을 충족해야 합니다.

* **CPU**: 4코어
* **RAM**: 16GB RAM
* **디스크 공간**: 36GB의 여유 디스크 공간




=== 서버 권장 사항

* 파일 시스템 생성을 위해 추가 디스크 공간을 할당하십시오. 파일 시스템에 최소 35GB의 여유 공간이 있는지 확인하십시오. + 만약 `/opt` NAS 저장소에서 마운트된 폴더이므로 로컬 사용자는 이 폴더에 대한 접근 권한이 있어야 합니다. 로컬 사용자에게 필요한 권한이 없는 경우 사용자 활동 에이전트 생성이 실패할 수 있습니다.
* 사용자 활동 에이전트는 Ransomware Resilience 환경과는 별도의 시스템에 설치하는 것이 좋습니다. 같은 시스템에 설치하는 경우 50~55GB의 디스크 공간을 허용해야 합니다. Linux의 경우 `/opt/netapp`에 25~30GB, `var/log/netapp`에 25GB의 공간을 할당하십시오.
* ONTAP 시스템과 사용자 활동 에이전트 시스템의 시간을 네트워크 시간 프로토콜(NTP) 또는 단순 네트워크 시간 프로토콜(SNTP)을 사용하여 동기화하는 것이 좋습니다.




=== 사이징 권장 사항

사용자 이벤트를 수집할 때는 사용자 활동 에이전트를 호스팅하는 시스템의 용량이 이벤트 처리 속도에 적합한지 확인해야 합니다. 즉, 초당 발생하는 이벤트 수를 감당할 수 있도록 충분한 데이터 수집기와 CPU 및 RAM을 사용자 활동 에이전트를 호스팅하는 시스템에 확보해야 합니다. 데이터 수집기 수를 늘리려면 RAM 또는 CPU 용량을 증설해야 할 수 있습니다. Ransomware Resilience는 사용자 활동 에이전트당 최대 50개의 데이터 수집기를 지원합니다.

다음 표에서는 크기 조정에 대한 일반적인 지침을 제공합니다.

|===
| 사용자 활동 에이전트 시스템 구성 | 데이터 수집기 수 | 최대 이벤트 속도 


| 4코어, 16GB | 데이터 수집기 10개 | 초당 20,000개의 이벤트 


| 4코어, 32GB | 데이터 수집기 20개 | 초당 20,000개의 이벤트 
|===
또한 특정 요구 사항을 계산할 수도 있습니다. 적절한 크기를 계산할 때는 30%의 버퍼 비율을 고려하여 검증하는 것이 좋습니다. 다음 공식을 사용하여 구성이 부하를 처리할 수 있는지 확인하십시오.

[listing]
----
Where E is the sum of all events per second across all data collectors:

E + (0.3 x E) < 20,000 events/second
----
.Ransomware Resilience는 이벤트 데이터 전송률을 계산하는 스크립트를 제공합니다. Ransomware Resilience에서 이벤트 데이터 전송률을 계산하는 방법을 알아보십시오.
[%collapsible]
====
Ransomware Resilience는 시스템에서 실행하여 이벤트 데이터 발생률을 계산할 수 있는 스크립트를 제공합니다. 기본적으로 이 스크립트는 최대 5개의 스토리지 VM에 대해 실행됩니다. 환경에 5개 이상의 SVM이 포함된 경우 스크립트를 적절히 수정할 수 있습니다. SVM 개수와 관계없이 스크립트는 평균 이벤트 발생률을 계산하는 데 약 5분이 소요됩니다. 스크립트를 실행하기 전에 다음 사항을 확인해야 합니다.

* link:suspicious-user-activity.html["사용자 활동 에이전트를 구성했습니다."]
* 클러스터 IP 주소
* 클러스터 관리자 사용자 이름 및 암호
* Linux 시스템에 설치됨 `sshpass`(명령줄 `sudo yum install -y sshpass`을 사용하여 설치할 수 있음)


.단계
. 사용자 활동 에이전트를 호스팅하는 클러스터에서 관리자 권한으로 스크립트를 실행하십시오. `/opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh`
. 메시지가 나타나면 클러스터 IP 주소, 관리자 사용자 이름 및 관리자 암호를 입력하십시오.
. 스크립트 실행에는 약 5분이 소요됩니다. 실행이 완료되면 명령줄에 이벤트 발생률이 표시됩니다(예: "Svm svm_rate is generating 100 events/sec.").
+
이벤트 속도를 사용하여 크기를 계산하십시오.



====


== 클라우드 네트워크 액세스 규칙

해당 지역(아시아 태평양, 유럽 또는 미국)의 클라우드 네트워크 액세스 규칙을 검토하십시오.


IMPORTANT: 초기 설치 시  `<site_name>`를 와일드카드 (`*` 권한으로 바꾸십시오. 에이전트가 활성화되어 완전히 작동되면 권한을 사이트 이름으로 바꿀 수 있습니다. 사이트 이름은 NetApp 담당자에게 문의하십시오.


NOTE: 사용자 활동 에이전트는 NetApp Data Infrastructure Insights 기술을 사용하므로 `cloudinsights` 엔드포인트를 사용합니다. 자세한 내용은 다음을 참조하십시오



=== APAC 기반 사용자 활동 에이전트 배포

[cols="1,1,1,3,1"]
|===
| 규약 | 포트 | 원천 | 목적지 | 설명 


| HTTPS(TCP) | 443 | 사용자 활동 에이전트  a| 
* <site_name>.cs01-ap-1.cloudinsights.netapp.com
* <site_name>.c01-ap-1.cloudinsights.netapp.com
* <site_name>.c02-ap-1.cloudinsights.netapp.com
* gentlogin.cs01-ap-1.cloudinsights.netapp.com

| 랜섬웨어 복원력에 대한 접근성 
|===


=== 유럽 기반 사용자 활동 에이전트 배포

[cols="1,1,1,3,1"]
|===
| 규약 | 포트 | 원천 | 목적지 | 설명 


| HTTPS(TCP) | 443 | 사용자 활동 에이전트  a| 
* <site_name>.cs01-eu-1.cloudinsights.netapp.com
* <site_name>.c01-eu-1.cloudinsights.netapp.com
* <site_name>.c02-eu-1.cloudinsights.netapp.com
* agentlogin.cs01-eu-1.cloudinsights.netapp.com

| 랜섬웨어 복원력에 대한 접근성 
|===


=== 미국 기반 사용자 활동 에이전트 배포

[cols="1,1,1,3,1"]
|===
| 규약 | 포트 | 원천 | 목적지 | 설명 


| HTTPS(TCP) | 443 | 사용자 활동 에이전트  a| 
* <site_name>.cs01.cloudinsights.netapp.com
* <site_name>.c01.cloudinsights.netapp.com
* <site_name>.c02.cloudinsights.netapp.com
* agentlogin.cs01.cloudinsights.netapp.com

| 랜섬웨어 복원력에 대한 접근성 
|===


== 네트워크 내 규칙

[cols="5*"]
|===
| 규약 | 포트 | 원천 | 목적지 | 설명 


| TCP | 389(LDAP) 636(LDAP/start-tls) | 사용자 활동 에이전트 | LDAP 서버 URL | LDAP에 연결 


| HTTPS(TCP) | 443 | 사용자 활동 에이전트 | 클러스터 또는 SVM 관리 IP 주소(SVM 컬렉터 구성에 따라 다름) | ONTAP 과의 API 통신 


| TCP | 35000 - 55000  a| 
SVM 데이터 LIF IP 주소
| 사용자 활동 에이전트 | Fpolicy 이벤트에 대한 ONTAP 에서 사용자 활동 에이전트로의 통신. ONTAP 사용자 활동 에이전트로 이벤트를 전송하려면 사용자 활동 에이전트 방향으로 이러한 포트가 열려 있어야 하며, 사용자 활동 에이전트 자체에 방화벽이 있는 경우에도 마찬가지입니다(있는 경우). + **참고:** 이 포트들을 *모두* 예약할 필요는 없지만, 예약하는 포트는 반드시 이 범위 내에 있어야 합니다. 우선 100개의 포트를 예약하고 필요에 따라 늘리는 것이 좋습니다. 


| TCP | 35000-55000 | 클러스터 관리 IP | 사용자 활동 에이전트 | ONTAP 클러스터 관리 IP에서 사용자 활동 에이전트로의 *EMS 이벤트* 통신. ONTAP EMS 이벤트를 사용자 활동 에이전트로 전송하려면 사용자 활동 에이전트 자체의 방화벽을 포함하여 이러한 포트가 사용자 활동 에이전트 방향으로 열려 있어야 합니다. + **참고:** 이 포트들을 *모두* 예약할 필요는 없지만, 예약하는 포트는 반드시 이 범위 내에 있어야 합니다. 우선 100개의 포트를 예약하고 필요에 따라 늘리는 것이 좋습니다. 


| SSH | 22 | 사용자 활동 에이전트 | 클러스터 관리 | CIFS/SMB 사용자 차단에 필요합니다. 
|===


== 다음 단계

* link:suspicious-user-activity.html["사용자 활동 에이전트 및 수집기 구성"]

