---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 
---
= NetApp Ransomware Resilience 의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.



== 준비 훈련 재설정 옵션 문제

랜섬웨어 공격 대비 훈련을 위해 ONTAP 9.11.1 볼륨을 선택하면 랜섬웨어 복원력에서 경고를 보냅니다.  "볼륨 복제" 옵션을 사용하여 데이터를 복구하고 드릴을 재설정하면 재설정 작업이 실패합니다.



== Amazon FSx for NetApp ONTAP 제한 사항

Amazon FSx for NetApp ONTAP 시스템은 랜섬웨어 복원력에서 지원됩니다. Amazon FSx for ONTAP 에는 다음과 같은 제한 사항이 적용됩니다.

* 백업 정책은 Amazon FSx for ONTAP에서 지원되지 않습니다. 이 환경에서는 Amazon FSx for backups를 사용하여 백업 작업을 수행해야 합니다. 이러한 워크로드는 NetApp Ransomware Resilience를 사용하여 복원할 수 있습니다.
* 복원 작업은 스냅샷에서만 수행됩니다.




== Azure NetApp Files 제한 사항

Azure NetApp Files는 Ransomware Resilience에서 지원됩니다. Azure NetApp Files에는 다음과 같은 제한 사항이 적용됩니다.

* 백업 정책을 사용하는 랜섬웨어 보호 전략은 Azure NetApp Files에서 지원되지 않습니다. 대신 Azure NetApp Files 백업을 사용할 수 있습니다.
* Azure NetApp Files에서는 복제 기능을 사용하는 랜섬웨어 보호 전략이 지원되지 않습니다.
* 보호 전략을 선택할 때는 스냅샷 일정이 Azure NetApp Files와 호환되는지 확인하십시오. Azure NetApp Files에서 사용할 수 있는 가장 빈번한 스냅샷 일정은 시간 단위입니다.

