---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: NetApp Ransomware Resilience 에 대한 자주 묻는 질문에 대한 답변을 찾아보세요. 
---
= NetApp Ransomware Resilience 에 대한 자주 묻는 질문
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience 에 대한 질문에 대한 빠른 답변을 찾고 있다면 이 FAQ가 도움이 될 수 있습니다.



== 전개

.랜섬웨어 복원력을 사용하려면 라이선스가 필요합니까?
다음 라이선스 유형을 사용할 수 있습니다.

* 30일 무료 체험판에 등록하세요.
* Amazon Web Services(AWS) Marketplace, Google Cloud Marketplace, Microsoft Azure Marketplace에서 NetApp Intelligent Services 및 Ransomware Resilience에 대한 종량제(PAYGO) 구독을 구매하세요.
* BYOL(Bring Your Own License)은 NetApp 영업 담당자로부터 받는 NetApp 라이선스 파일(NLF)입니다. 콘솔의 Licenses and subscriptions 섹션에서 라이선스 일련 번호를 사용하여 BYOL을 활성화할 수 있습니다.


.랜섬웨어 복원력을 어떻게 활성화하나요?
NetApp Console 에서 랜섬웨어 복원력에 액세스할 수 있습니다. 당신이 가지고 있는지 확인하십시오 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["액세스 역할"] 그리고 link:rp-start-prerequisites.html["전제 조건"]. 콘솔 에이전트를 성공적으로 구성했다면 다음을 수행할 수 있습니다. link:rp-start-discover.html["워크로드 검색"].

자세한 내용은 다음을 참조하세요.link:rp-start-login.html["랜섬웨어 복원력에 액세스"] 그리고link:rp-start-quick-start.html["랜섬웨어 복원력 빠른 시작 가이드"] .

.랜섬웨어 복원력을 표준, 제한, 비공개 모드로 사용할 수 있나요?
랜섬웨어 복원력은 현재 표준 모드에서만 사용할 수 있습니다.

모든 NetApp 데이터 서비스에서 이러한 모드에 대한 설명은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console 배포 모드"^] .



== 입장

.랜섬웨어 복구 URL은 무엇인가요?
브라우저에서 다음을 입력하세요. https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] 콘솔에 접속하려면.

.접근 권한은 어떻게 처리되나요?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 콘솔 액세스 역할에 대해 알아보세요."^]. 랜섬웨어 복원력도 있습니다 link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["전담 액세스 역할"^].

.어떤 기기의 해상도가 가장 좋은가요?
랜섬웨어 복원력에 권장되는 장치 해상도는 1920x1080 이상입니다.

.어떤 브라우저를 사용해야 하나요?
모든 최신 웹 브라우저를 사용하여 NetApp Console 에 액세스할 수 있습니다.



== 상호 운용성

.랜섬웨어 복원력은 NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?
네, 랜섬웨어 복원력은 ONTAP 에 설정된 스냅샷 일정을 검색합니다.

.랜섬웨어 복원력은 NetApp Backup and Recovery 와 SnapCenter 와 어떻게 상호 작용합니까?
랜섬웨어 복원력은 백업 및 복구와 함께 작동하여 파일 공유 작업 부하에 대한 스냅샷 및 백업 정책을 검색하고 설정합니다.

랜섬웨어 복원력은 SnapCenter 또는 SnapCenter for VMware와 함께 작동하여 애플리케이션 및 VM 워크로드에 대한 스냅샷 및 백업 정책을 검색하고 설정합니다.

Ransomware Resilience는 백업 및 복구와 SnapCenter (VMware용 SnapCenter 포함)와도 연동하여 파일과 워크로드에 일관된 복구를 수행합니다.



== 작업 부하

.랜섬웨어 복원력의 맥락에서 워크로드란 무엇입니까?
워크로드는 애플리케이션, VM 또는 파일 공유입니다. 작업 부하에는 단일 애플리케이션 인스턴스에서 사용되는 모든 볼륨이 포함됩니다.

예를 들어 ora3.host.com에 배포된 Oracle 데이터베이스를 고려해 보세요. `vol1` 데이터를 포함하고 `vol2` 로그를 포함하고 있습니다. 두 볼륨은 해당 Oracle Database 인스턴스의 작업 부하를 구성합니다.

.랜섬웨어 복원력은 어떻게 워크로드 데이터의 우선 순위를 정합니까?
워크로드 우선순위(중요, 표준, 중요)는 워크로드와 예약된 백업에 연결된 각 볼륨에 이미 적용된 스냅샷 빈도에 따라 결정됩니다.

link:rp-use-protect.html["작업 우선순위 또는 중요도에 대해 알아보세요"] .

.Ransomware Resilience는 어떤 작업 부하를 지원합니까?
랜섬웨어 복원력은 다음과 같은 작업 부하를 식별할 수 있습니다: Oracle, MySQL, 파일 공유, 블록 스토리지, VM 및 VM 데이터 저장소.

SnapCenter 또는 SnapCenter for VMware를 사용하는 경우 이러한 제품에서 지원하는 모든 워크로드는 랜섬웨어 복원력에서도 식별됩니다. 랜섬웨어 복원력은 SnapCenter 및 SnapCenter 워크로드를 워크로드에 맞춰 일관되게 보호하고 복구할 수 있습니다.

.데이터를 작업 부하와 어떻게 연관시키나요?
랜섬웨어 복원력은 볼륨과 파일 확장자를 검색하여 적절한 작업 부하와 연결합니다.

SnapCenter 또는 SnapCenter for VMware가 있고 백업 및 복구에서 워크로드를 구성한 경우 Ransomware Resilience는 SnapCenter 및 SnapCenter for VMware와 관련 볼륨에서 관리하는 워크로드를 검색합니다.

.보호된 작업 부하란 무엇입니까?
랜섬웨어 복원력에서 작업 부하가 기본 _탐지_ 정책이 활성화된 경우 *보호됨* 상태를 표시합니다. link:concept-ransomware-resilience.html["자율 랜섬웨어 보호(ARP)"] 작업 부하와 관련된 모든 볼륨에서 활성화됩니다.

."위험에 처한" 작업 부하란 무엇입니까?
워크로드에 기본 감지 정책이 활성화되어 있지 않으면 백업 및 스냅샷 정책이 활성화되어 있어도 "위험"으로 표시됩니다. 랜섬웨어 보호를 위해서는 다음을 활성화해야 합니다. link:rp-use-protect.html#add-a-ransomware-protection-strategy["탐지 정책"].

.새로운 볼륨을 추가했지만 아직 나타나지 않았습니다. 어떻게 해야 하나요?
환경에 새 볼륨을 추가한 경우 워크로드 검색을 다시 시작합니다. 볼륨이 발견된 후, link:rp-use-protect.html#add-a-ransomware-protection-strategy["새 볼륨을 보호하기 위해 보호 정책을 적용합니다."].



== 보호 정책

.랜섬웨어 복원력 랜섬웨어 정책은 다른 종류의 워크로드 정책과 공존할 수 있나요?
현재 백업 및 복구(클라우드 백업)는 볼륨당 하나의 백업 정책을 지원합니다. 백업 및 복구를 사용하여 백업 보호를 구성하는 경우 랜섬웨어 복원력과 백업 정책을 공유합니다.

스냅샷 사본은 제한이 없으며 각 서비스에서 별도로 추가할 수 있습니다.

.랜섬웨어 보호 전략에는 어떤 정책이 필요합니까?
에이 link:rp-use-protect.html#add-a-ransomware-protection-strategy["랜섬웨어 보호 전략"] 필요사항:

* 랜섬웨어 탐지 정책 및
* 스냅샷 정책


랜섬웨어 복원력 전략에는 백업 정책이 필요하지 않습니다.

.랜섬웨어 복원력은 NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?
네, 랜섬웨어 복원력은 ONTAP 에 설정된 스냅샷 일정을 검색합니다. 또한 검색된 작업 부하의 모든 볼륨에서 ARP와 FPolicy가 활성화되어 있는지도 알아냅니다. 랜섬웨어 복원력 대시보드에 표시되는 정보는 다른 NetApp 솔루션 및 제품에서 집계된 것입니다.

.Ransomware Resilience는 백업 및 복구와 SnapCenter 에서 이미 만들어진 정책을 알고 있습니까?
네, 백업 및 복구 또는 SnapCenter 에서 관리되는 워크로드가 있는 경우 해당 제품에서 관리하는 정책이 Ransomware Resilience로 적용됩니다.

.NetApp Backup and Recovery 및/또는 SnapCenter 에서 가져온 정책을 수정할 수 있나요?
아니요, Ransomware Resilience의 Backup and Recovery 또는 SnapCenter 에서 관리하는 정책은 수정할 수 없습니다.  해당 정책에 대한 변경 사항은 백업 및 복구 또는 SnapCenter 에서 관리합니다.

.ONTAP 의 정책(예: ARP, FPolicy, 스냅샷)이 있는 경우 랜섬웨어 복원력에서 해당 정책이 변경됩니까?
아니요. 랜섬웨어 복원력은 ONTAP 의 기존 탐지 정책(ARP, FPolicy 설정)을 수정하지 않습니다.

.랜섬웨어 복원력에 가입한 후 백업 및 복구 또는 SnapCenter 에 새로운 정책을 추가하면 어떻게 되나요?
랜섬웨어 복원력은 백업 및 복구 또는 SnapCenter 에서 새로 생성된 정책과 정책 변경 사항을 인식합니다.

.ONTAP 에서 정책을 변경할 수 있나요?
네, ONTAP 에서 Ransomware Resilience 정책을 변경할 수 있습니다.  랜섬웨어 복원력에서 새로운 정책을 만들어 워크로드에 적용할 수도 있습니다.  이 작업은 기존 ONTAP 정책을 Ransomware Resilience에서 생성된 정책으로 대체합니다.

.ONTAP 에서 정책을 비활성화할 수 있나요?
ONTAP 의 시스템 관리자 UI, API 또는 CLI를 사용하여 탐지 정책에서 ARP를 비활성화할 수 있습니다.

FPolicy 및 백업 정책을 비활성화하려면 해당 정책을 포함하지 않는 다른 정책을 적용하면 됩니다.
