---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: 랜섬웨어 복원력을 사용하려면 몇 가지 단계를 거쳐 설정하세요. 
---
= NetApp Ransomware Resilience 설정
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience 쉽게 배포할 수 있습니다. 시작하기 전에 검토하세요link:rp-start-prerequisites.html["전제 조건"] 귀하의 환경이 준비되었는지 확인하세요.



== 백업 대상을 준비하세요

다음 백업 대상 중 하나를 준비하세요.

* NetApp StorageGRID
* 아마존 웹 서비스
* 구글 클라우드 플랫폼
* 마이크로소프트 애저


백업 대상지 자체에서 옵션을 구성한 후 나중에 Ransomware Resilience에서 백업 대상으로 구성하게 됩니다.  Ransomware Resilience에서 백업 대상을 구성하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:rp-use-settings.html["백업 대상 구성"] .



=== StorageGRID 백업 대상으로 준비

StorageGRID 백업 대상으로 사용하려면 다음을 참조하세요. https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID 문서"^] StorageGRID 에 대한 자세한 내용은 다음을 참조하세요.



=== AWS를 백업 대상으로 준비

* AWS에 계정을 설정합니다.
* 구성 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS 권한"^] AWS에서.


콘솔에서 AWS 스토리지를 관리하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Amazon S3 버킷 관리"^] .



=== Azure를 백업 대상으로 준비

* Azure에 계정을 설정합니다.
* 구성 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 권한"^] Azure에서.


콘솔에서 Azure 저장소를 관리하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Azure 저장소 계정 관리"^] .



== NetApp Console 설정

다음 단계는 콘솔과 랜섬웨어 복원력을 설정하는 것입니다.

검토 https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["표준 모드에 대한 콘솔 요구 사항"^] .



=== 콘솔 에이전트 만들기

이 서비스를 체험하거나 사용하려면 NetApp 영업 담당자에게 문의하세요.  그런 다음 콘솔 에이전트를 사용하면 랜섬웨어 복원력에 적합한 기능이 포함됩니다.

Ransomware Resilience를 사용하여 콘솔 에이전트를 생성하려면 콘솔 에이전트를 생성할 권한이 있는 콘솔 조직 관리자에게 문의하고 해당 내용을 설명하는 설명서를 참조하십시오. https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["콘솔 에이전트를 만드는 방법"^] .


NOTE: 콘솔 에이전트가 여러 개 있는 경우 랜섬웨어 복원력 검사 데이터는 현재 콘솔에 표시되는 에이전트를 제외한 모든 콘솔 에이전트에서 수집됩니다.  이 서비스는 이 조직과 관련된 모든 프로젝트와 모든 콘솔 에이전트를 검색합니다.
