---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, 
summary: NetApp Ransomware Resilience에서 사용자 디렉터리 커넥터를 생성한 후에는 사용자를 차단 및 차단 해제하고 알림에서 사용자를 제외할 수 있습니다. 
---
= NetApp Ransomware Resilience에서 사용자 차단 및 알림 관리
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience에서 사용자 디렉터리 커넥터를 생성한 후에는 랜섬웨어 이벤트가 발생할 때 사용자를 차단하거나 차단 해제하고 평가할 수 있습니다. 또한 사용자의 행동이 공격이 아니라고 확신하는 경우 랜섬웨어 경고에서 해당 사용자를 선택적으로 제외할 수도 있습니다.

사용자를 차단하려면 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["사용자 활동 에이전트를 구성하고, 사용자 활동 감지 기능을 포함하는 정책을 활성화하고, 사용자 디렉터리 커넥터를 생성했습니다."]이(가) 있어야 합니다.


TIP: link:task-automate-user-activity.html["응답 자동화"] 사용자 활동 감지 이벤트에 적용할 수 있습니다.



== 차단된 사용자 관리

악의적인 활동에 책임이 있다고 판단되는 사용자를 차단할 수 있습니다.

.사용자 차단
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **사용자** 탭을 선택합니다.
. **사용자 차단**을 선택합니다.
. 차단 기간을 선택하세요. 1시간부터 최대 24시간 또는 영구적으로 차단할 수 있습니다.
. 차단하려는 사용자 이름 옆의 확인란을 선택합니다.
. **차단**을 선택합니다.


.차단된 사용자 목록 수정
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **사용자** 탭을 선택합니다.
. **사용자 차단 편집**을 선택합니다.
. 수정 방법을 선택하세요. 차단 기간을 수정하려면 **차단 사용자 기간**을 선택한 다음 기간을 수정하세요. 차단된 사용자 목록에서 사용자를 제거하려면 **사용자 차단 해제**를 선택하세요.
. 차단 상태를 변경하려는 차단된 사용자 이름 옆의 확인란을 선택합니다.
. **저장**을 선택합니다.




== 사용자 알림 관리

특정 신뢰할 수 있는 사용자의 동작이 사용자 동작 알림을 트리거할 수 있는 경우 알림에서 해당 사용자를 제외할 수 있습니다.

.알림에서 사용자 제외
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **모니터링 제외** 탭을 선택합니다.
. UI에서 개별 사용자를 검토하려면 **수동 선택**을 선택하십시오. 제외된 사용자 목록을 업로드하려면 **업로드**를 선택하십시오.
+
.. **수동 선택**을 선택한 경우 제외할 특정 사용자 이름 옆의 확인란을 선택하십시오.
.. **업로드**를 선택하면 모든 사용자 목록이 포함된 CSV 또는 JSON 파일을 다운로드할 수 있습니다. **다운로드**를 선택하면 목록에 액세스할 수 있습니다.
+
로컬 컴퓨터에서 파일을 검토합니다. 탐지를 유지할 모든 사용자의 이름을 제거합니다. 목록에 탐지에서 제외할 사용자의 이름만 포함되면 저장합니다.

+
Ransomware Resilience에서 **업로드**를 선택합니다. 파일을 찾아 업로드합니다.



. 사용자를 제외 목록에 추가하려면 **추가**를 선택하십시오.
. **모니터링에서 제외됨** 탭에서 사용자 행동 감지 알림에서 제거된 사용자의 이름이 이제 대시보드에 표시됩니다.



TIP: 알림에서 사용자를 직접 제외할 수도 있습니다. 자세한 내용은 link:rp-use-alert.html["랜섬웨어 경고에 대응하세요"]를 참조하세요.

.제외 사용자 목록에서 사용자를 제거합니다
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **모니터링 제외** 탭을 선택합니다.
. **추가**를 선택합니다.
. 사용자 인터페이스에서 개별 사용자를 제외하려면 **수동으로 선택**을 선택하세요.
. 제외 사용자 목록에서 제거하려는 사용자의 이름을 찾으세요. 해당 사용자 이름이 있는 행에서 작업 메뉴((`...`)를 선택한 다음 **제거**를 선택하세요.
. 대화 상자에서 **Remove**를 선택하여 선택한 사용자를 제거할지 확인합니다.




== 다음 단계

* link:task-automate-user-activity.html["사용자 활동 감지 이벤트에 대한 응답 자동화"]

