---
sidebar: sidebar 
permalink: task-automate-user-activity.html 
keywords: data breach detection, data breach, user activity, automated response 
summary: NetApp Ransomware Resilience는 사용자 활동 이벤트에 대한 자동 대응 생성을 지원하여 스냅샷을 자동으로 생성하거나 사용자를 차단할 수 있도록 합니다. 
---
= NetApp Ransomware Resilience에서 사용자 활동 알림에 대한 대응 자동화
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience는 link:concept-user-behavior.html["사용자 활동 이벤트"]에 대한 자동화된 대응 생성을 지원합니다. 자동화된 대응 기능을 통해 Ransomware Resilience는 공격이나 경고가 감지될 때 스냅샷을 생성하거나 사용자를 차단하여 랜섬웨어 이벤트에 더욱 신속하게 대응할 수 있도록 합니다.

암호화(사용자 행동), 데이터 유출 및 데이터 삭제 이벤트에 대한 자동 응답이 지원됩니다. 자동 응답을 생성하기 전에 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["사용자 활동 에이전트를 구성하고, 사용자 활동 감지 기능을 포함하는 정책을 활성화하고, 사용자 디렉터리 커넥터를 생성했습니다."]이(가) 있어야 합니다.



== 자동 응답 생성

의심스러운 사용자 행동 감지 정책으로 보호되는 워크로드가 하나 이상 있는 스토리지 VM은 하나만 보호할 수 있습니다.

.단계
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 사용자 활동 모니터링 타일에서 **관리**를 선택합니다.
. **자동 응답** 탭을 선택합니다.
. 동작을 생성하려면 **추가**를 선택합니다.
. 자동 응답에 표시될 **이름**을 입력하세요.
. 응답을 트리거할 이벤트 유형을 선택하세요. **공격** 또는 **경고**. 다양한 link:rp-use-alert.html#alert-types-and-statuses["알림 유형"]에 대해 자세히 알아보세요.
. 답변을 선택하세요:
+
** **사용자 접근 차단**: 경고가 발생하면 해당 사용자는 Ransomware Resilience로 보호되는 모든 스토리지 VM에 대한 접근이 차단됩니다.
+
이 옵션을 선택하는 경우 차단 기간도 선택해야 합니다. 1시간에서 24시간 사이의 간격 또는 영구 차단을 선택할 수 있습니다.

** **스냅샷 생성**: 영향을 받는 워크로드에 대한 스냅샷을 생성하여 잠재적인 복구에 사용하십시오. 스냅샷은 7일 동안 보존됩니다.


. 자동 응답을 트리거하는 알림 유형을 선택하십시오.
+
|===


| 알림 유형 | 설명 


| 암호화(사용자 동작) | 랜섬웨어 복원력은 특정 사용자가 수행한 비정상적인 파일 읽기, 쓰기 및 이름 바꾸기 활동을 식별합니다. 


| 데이터 유출 | NetApp Ransomware Resilience는 특정 사용자가 수행하는 비정상적인 파일 읽기 액세스 패턴을 감지합니다. 


| 데이터 파기 | NetApp Ransomware Resilience는 특정 사용자에 의한 대량 파일 삭제를 감지합니다. 
|===
. 자동 응답을 적용할 스토리지 VM을 선택하십시오.
. 자동 응답을 생성하려면 **추가**를 선택하세요.




== 자동 응답 수정

자동 응답을 생성한 후에는 응답을 일시 중지하거나 다시 시작하거나 수정할 수 있습니다. 응답 이름, 응답을 트리거하는 알림 유형, 스토리지 VM 및 수행되는 작업을 수정할 수 있습니다.

.단계
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 사용자 활동 모니터링 타일에서 **관리**를 선택합니다.
. **자동 응답** 탭을 선택합니다.
. 수정할 자동 응답을 선택하세요.
. 응답을 일시 중지하거나 삭제하려면 작업 메뉴를 선택한 다음 **일시 중지**(또는 **시작**) 또는 **삭제**를 선택하십시오.
+
답변을 수정하려면 **편집**을 선택하세요.

. 경고 심각도를 제외한 모든 설정을 수정할 수 있습니다.
. 변경 사항을 저장하려면 **저장**을 선택하세요.

