---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, 
summary: NetApp Ransomware Resilience에서 사용자 디렉터리 커넥터를 생성한 후에는 사용자를 차단 및 차단 해제하고 경고에서 사용자를 제외할 수 있습니다. 또한 파일 경로에 대한 경고 생성을 제외할 수도 있습니다. 
---
= NetApp Ransomware Resilience에서 경고 및 차단된 사용자 관리
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience에서 사용자 행동 모니터링을 구성한 후에는 알림을 사용자 지정하고 차단된 사용자를 관리할 수 있습니다. 알림을 사용자 지정하면 특정 사용자 또는 파일 경로에 대한 알림 생성을 제외할 수 있습니다. 사용자 차단 기능은 랜섬웨어 공격에 대응하여 악의적인 사용자 활동을 방지하기 위한 것입니다.

사용자를 차단하려면 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["사용자 활동 에이전트를 구성하고, 사용자 활동 감지 기능을 포함하는 정책을 활성화하고, 사용자 디렉터리 커넥터를 생성했습니다."]이(가) 있어야 합니다.


TIP: link:task-automate-user-activity.html["응답 자동화"] 사용자 활동 감지 이벤트에 적용할 수 있습니다.



== 차단된 사용자 관리

악의적인 활동에 책임이 있다고 판단되는 사용자를 차단할 수 있습니다.

.사용자 차단
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **사용자** 탭을 선택합니다.
. **사용자 차단**을 선택합니다.
. 차단 기간을 선택하세요. 1시간부터 최대 24시간 또는 영구적으로 차단할 수 있습니다.
. 차단하려는 사용자 이름 옆의 확인란을 선택합니다.
. **차단**을 선택합니다.


.차단된 사용자 목록 수정
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **사용자** 탭을 선택합니다.
. **사용자 차단 편집**을 선택합니다.
. 수정 방법을 선택하세요. 차단 기간을 수정하려면 **차단 사용자 기간**을 선택한 다음 기간을 수정하세요. 차단된 사용자 목록에서 사용자를 제거하려면 **사용자 차단 해제**를 선택하세요.
. 차단 상태를 변경하려는 차단된 사용자 이름 옆의 확인란을 선택합니다.
. **저장**을 선택합니다.




== 알림에서 사용자 제외

특정 신뢰할 수 있는 사용자의 동작이 사용자 동작 알림을 트리거할 수 있는 경우 알림에서 해당 사용자를 제외할 수 있습니다.

.알림에서 사용자 제외
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 설정 대시보드에서 사용자 활동 모니터링 타일을 찾은 다음 **관리**를 선택합니다.
. **모니터링 제외** 탭을 선택합니다.
. UI에서 개별 사용자를 검토하려면 **수동 선택**을 선택하십시오. 제외된 사용자 목록을 업로드하려면 **업로드**를 선택하십시오.
+
.. **수동 선택**을 선택한 경우 제외할 특정 사용자 이름 옆의 확인란을 선택하십시오.
.. **업로드**를 선택하면 모든 사용자 목록이 포함된 CSV 또는 JSON 파일을 다운로드할 수 있습니다. **다운로드**를 선택하면 목록에 액세스할 수 있습니다.
+
로컬 컴퓨터에서 파일을 검토합니다. 탐지를 유지할 모든 사용자의 이름을 제거합니다. 목록에 탐지에서 제외할 사용자의 이름만 포함되면 저장합니다.

+
Ransomware Resilience에서 **업로드**를 선택합니다. 파일을 찾아 업로드합니다.



. 사용자를 제외 목록에 추가하려면 **추가**를 선택하십시오.
. **모니터링에서 제외됨** 탭에서 사용자 행동 감지 알림에서 제거된 사용자의 이름이 이제 대시보드에 표시됩니다.



TIP: 알림에서 사용자를 직접 제외할 수도 있습니다. 자세한 내용은 link:rp-use-alert.html["랜섬웨어 경고에 대응하세요"]를 참조하세요.

.제외 사용자 목록에서 사용자 제거
. 설정 대시보드에서 사용자 활동 카드를 찾은 다음 **관리**를 선택합니다.
. **모니터링 제외** 탭을 선택합니다.
. **추가**를 선택합니다.
. UI에서 개별 사용자를 제외하려면 **수동으로 선택**을 선택하십시오.
. 제외된 사용자 선택에서 제거하려는 사용자의 이름을 찾습니다. 해당 사용자 이름이 있는 행에서 작업 메뉴((`...`)를 선택한 다음 **제거**를 선택하세요.
. 대화 상자에서 **Remove**를 선택하여 선택한 사용자를 제거할지 확인합니다.




== 파일 경로를 모니터링에서 제외

각 파일 경로는 볼륨 이름으로 시작해야 합니다. 해당 볼륨에 대해 최대 세 개의 하위 디렉터리를 포함할 수 있으며, 예를 들어 "volume/directory/subdirectory/subdirectory2"와 같습니다. 파일 경로를 수동으로 입력하거나 경로 목록이 포함된 CSV 파일을 업로드하여 제외할 수 있습니다.

.단계
. 랜섬웨어 복원력에서 **설정**을 선택하세요.
. 사용자 활동 모니터링 타일에서 **관리**를 선택합니다.
. *모니터링 제외* 탭을 선택합니다.
. 제외할 파일 경로를 입력하려면 **추가**를 선택하세요.
. 사용자 인터페이스에서 파일 경로를 입력하려면 *수동 입력* 라디오 버튼을 선택한 다음 "volume/directory/subdirectory/"와 같이 파일 경로를 입력하십시오. 추가 파일 경로를 입력하려면 **파일 경로 선택**을 선택하십시오.
. 파일 경로 목록을 업로드하려면 **업로드** 라디오 버튼을 선택하세요. 업로드 버튼을 선택하여 CSV 파일을 선택하세요.
. **추가**를 선택합니다.


.결과
작업이 성공적으로 완료되면 Ransomware Resilience는 선택한 경로에 있는 파일을 의심스러운 사용자 동작 감시 대상에서 제외하기 시작합니다.  설정 메뉴에서 언제든지 경로 목록을 확인할 수 있습니다.  파일 경로에 대한 감시를 다시 활성화해야 하는 경우 목록에서 해당 경로를 제거하면 됩니다.



== 다음 단계

* link:task-automate-user-activity.html["사용자 활동 감지 이벤트에 대한 응답 자동화"]

