= Data Infrastructure Insights Storage Workload Security를 ​​사용하여 비정상적인 사용자 동작을 감지합니다.
:allow-uri-read: 




=== Data Infrastructure Insights Storage Workload Security를 ​​사용하여 비정상적인 사용자 동작을 감지합니다.

이 릴리스에서는 Data Infrastructure Insights Storage Workload Security를 ​​사용하여 스토리지 워크로드에서 비정상적인 사용자 동작을 감지할 수 있습니다.  이 기능은 잠재적인 보안 위협을 식별하고 잠재적으로 악의적인 사용자를 차단하여 데이터를 보호하는 데 도움이 됩니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 경고에 대응하세요"] .

Data Infrastructure Insights Storage Workload Security를 ​​사용하여 비정상적인 사용자 동작을 감지하기 전에 BlueXP ransomware protection *설정* 옵션을 사용하여 옵션을 구성해야 합니다.

참조하다 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["BlueXP ransomware protection 설정 구성"] .



=== 검색하고 보호할 작업 부하 선택

이 릴리스를 사용하면 이제 다음 작업을 수행할 수 있습니다.

* 각 커넥터 내에서 워크로드를 검색할 작업 환경을 선택합니다.  환경 내 특정 작업 부하만 보호하고 다른 작업 부하에는 영향을 미치지 않으려는 경우 이 기능이 유용할 수 있습니다.
* 워크로드 검색 중에 커넥터별로 워크로드를 자동으로 검색하도록 설정할 수 있습니다.  이 기능을 사용하면 보호하려는 작업 부하를 선택할 수 있습니다.
* 이전에 선택한 작업 환경에 대해 새로 생성된 작업 부하를 찾아보세요.


참조하다 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["워크로드 검색"] .
