= 공격을 시뮬레이션하고 대응하세요
:allow-uri-read: 




=== 공격을 시뮬레이션하고 대응하세요

이 릴리스에서는 랜섬웨어 경고에 대한 대응을 테스트하기 위해 랜섬웨어 공격을 시뮬레이션합니다.  이 기능은 경고 알림, 대응 및 복구 프로세스를 테스트하여 실제 랜섬웨어 공격이 발생할 경우 대비가 되어 있는지 확인하는 데 도움이 됩니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 대비 훈련을 실시하세요"] .



=== 발견 프로세스 개선

이 릴리스에는 선택적 검색 및 재발견 프로세스에 대한 개선 사항이 포함되어 있습니다.

* 이 릴리스에서는 이전에 선택한 작업 환경에 추가된 새로 생성된 워크로드를 검색할 수 있습니다.
* 이번 릴리스에서는 _새로운_ 작업 환경을 선택할 수도 있습니다.  이 기능은 환경에 추가된 새로운 워크로드를 보호하는 데 도움이 됩니다.
* 이러한 검색 프로세스는 초기 검색 프로세스 중에 또는 설정 옵션 내에서 수행할 수 있습니다.


자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["이전에 선택한 작업 환경에 대해 새로 생성된 작업 부하를 검색합니다."] 그리고 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["설정 옵션을 사용하여 기능 구성"] .



=== 높은 암호화가 감지되면 경고가 발생합니다.

이 릴리스를 사용하면 높은 수준의 파일 확장자를 변경하지 않아도 워크로드에서 높은 수준의 암호화가 감지되면 알림을 볼 수 있습니다.  ONTAP Autonomous Ransomware Protection(ARP) AI를 사용하는 이 기능은 랜섬웨어 공격 위험이 있는 워크로드를 식별하는 데 도움이 됩니다.  이 기능을 사용하면 확장자가 변경되었는지 여부와 관계없이 영향을 받은 파일의 전체 목록을 다운로드할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["감지된 랜섬웨어 경고에 대응하세요"] .
