= 랜딩 페이지 업데이트
:allow-uri-read: 




=== 랜딩 페이지 업데이트

이번 릴리스에는 BlueXP ransomware protection 의 랜딩 페이지가 업데이트되어 무료 평가판 시작과 검색이 더욱 쉬워졌습니다.



=== 준비 훈련 업데이트

이전에는 새로운 샘플 워크로드에 대한 공격을 시뮬레이션하여 랜섬웨어 대비 훈련을 실행할 수 있었습니다.  이 기능을 사용하면 시뮬레이션된 공격을 조사하고 작업 부하를 복구할 수 있습니다.  이 기능을 사용하여 경고 알림, 대응 및 복구를 테스트하세요.  필요한 만큼 자주 이 훈련을 실행하고 일정을 잡으세요.

이번 릴리스에서는 BlueXP ransomware protection 대시보드의 새 버튼을 사용하여 테스트 워크로드에 대한 랜섬웨어 준비 훈련을 실행할 수 있습니다. 이를 통해 제어된 환경 내에서 랜섬웨어 공격을 시뮬레이션하고, 그 영향을 조사하고, 워크로드를 효율적으로 복구하기가 더 쉬워졌습니다.

이제 NFS 워크로드뿐만 아니라 CIFS(SMB) 워크로드에 대한 준비 훈련을 실행할 수 있습니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["랜섬웨어 공격 대비 훈련을 실시하세요"] .



=== BlueXP classification 업데이트 활성화

BlueXP ransomware protection 서비스 내에서 BlueXP classification 사용하기 전에 BlueXP classification 활성화하여 데이터를 검사해야 합니다.  데이터를 분류하면 개인 식별 정보(PII)를 찾는 데 도움이 되며, 이는 보안 위험을 증가시킬 수 있습니다.

BlueXP ransomware protection 내에서 파일 공유 워크로드에 BlueXP classification 배포할 수 있습니다.  *개인정보 노출* 열에서 *노출 식별* 옵션을 선택합니다.  분류 서비스를 활성화한 경우 이 작업을 통해 노출을 식별할 수 있습니다.  그렇지 않은 경우, 이 릴리스에서는 대화 상자에 BlueXP classification 배포할 수 있는 옵션이 표시됩니다.  *배포*를 선택하면 BlueXP classification 서비스 랜딩 페이지로 이동하여 해당 서비스를 배포할 수 있습니다.  여

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["클라우드에 BlueXP classification 배포"^] BlueXP ransomware protection 서비스를 사용하려면 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["BlueXP classification 사용하여 개인 식별 정보를 스캔하세요"] .
