= Amazon FSx for NetApp ONTAP 지원
:allow-uri-read: 




=== Amazon FSx for NetApp ONTAP 지원

이 릴리스는 Amazon FSx for NetApp ONTAP 지원합니다.  이 기능은 BlueXP ransomware protection 기능으로 FSx for ONTAP 워크로드를 보호하는 데 도움이 됩니다.

FSx for ONTAP 클라우드에서 NetApp ONTAP 스토리지의 성능을 제공하는 완전 관리형 서비스입니다.  온프레미스에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 제공하며, 기본 AWS 서비스의 민첩성과 확장성을 갖추고 있습니다.

BlueXP ransomware protection 워크플로에 다음과 같은 변경 사항이 적용되었습니다.

* Discovery에는 FSx for ONTAP 9.15 작업 환경의 워크로드가 포함됩니다.
* 보호 탭에는 FSx for ONTAP 환경의 워크로드가 표시됩니다.  이 환경에서는 FSx for ONTAP 백업 서비스를 사용하여 백업 작업을 수행해야 합니다.  BlueXP ransomware protection 스냅샷을 사용하여 이러한 작업 부하를 복원할 수 있습니다.
+

TIP: FSx for ONTAP 에서 실행되는 워크로드에 대한 백업 정책은 BlueXP 에서 설정할 수 없습니다.  Amazon FSx for NetApp ONTAP 에 설정된 기존 백업 정책은 변경되지 않습니다.

* 경고 사건은 새로운 FSx for ONTAP 작업 환경을 보여줍니다.


자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["BlueXP ransomware protection 및 작업 환경에 대해 알아보세요"] .

지원되는 옵션에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["BlueXP ransomware protection 제한 사항"] .



=== BlueXP 액세스 역할이 필요합니다

이제 BlueXP ransomware protection 보고, 검색하고, 관리하려면 다음 액세스 역할 중 하나가 필요합니다. 조직 관리자, 폴더 또는 프로젝트 관리자, 랜섬웨어 보호 관리자 또는 랜섬웨어 보호 뷰어.

https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 BlueXP 액세스 역할에 대해 알아보세요"^] .
