= 
:allow-uri-read: 


.클린룸 SVM 데이터 LIF IP(crr-data-LIF-IP)
* 클린룸 SVM 데이터 LIF에 IP 주소를 할당하십시오. IP 주소를 기록해 두십시오. IRE 구성 과정에서 이 IP 주소가 필요합니다.
+
** AWS를 사용하는 Cloud Volumes ONTAP에서 클라우드 간 클린 복원을 사용하는 경우 IP 주소가 Elastic Network Interface에 할당되었는지 확인하십시오.


* SVM 데이터 LIF IP에서 IRE로의 라우팅을 허용합니다.



NOTE: Amazon FSxN for ONTAP에서 소스를 사용하여 IRE를 구성하는 경우 이 클린룸 SVM 데이터 LIF IP 요구 사항을 건너뛰십시오.

.운영 환경 라우팅 테이블
* 운영 환경 라우팅 테이블은 IRE 서브넷에서 클린 복원 데이터 LIF IP로의 트래픽을 허용해야 합니다. 이 경로를 운영 환경 라우팅 테이블에 추가해야 합니다.
* 운영 ONTAP 클러스터의 보안 그룹 및 방화벽은 클린 복원 데이터 LIF IP로 향하는 NFSv4 및 NFSv3 인바운드 트래픽을 허용해야 합니다. 방화벽은 IRE CIDR 범위에서 들어오는 트래픽을 허용하도록 열려 있어야 합니다.
+
[cols="1,1,1,1"]
|===
| 규약 | 대상 포트 | 원천 | 목적 


| TCP 및 UDP | 2049 | IRE VPC CIDR 범위 | IRE에서 NFSv4 액세스 


| TCP 및 UDP | 111 | IRE VPC CIDR 범위 | IRE에서 NFSv3 액세스 


| TCP 및 UDP | 635 | IRE VPC CIDR 범위 | IRE에서 NFSv3 액세스 


| TCP 및 UDP | 4045 | IRE VPC CIDR 범위 | IRE에서 NFSv3 액세스 


| TCP 및 UDP | 4046 | IRE VPC CIDR 범위 | IRE에서 NFSv3 액세스 


| TCP 및 UDP | 4049 | IRE VPC CIDR 범위 | IRE에서 NFSv3 액세스 
|===


.IRE 라우팅 테이블
* IRE 라우팅 테이블은 IRE VPC의 기본 라우팅 테이블이어야 합니다.
* IRE 라우팅 테이블은 클린 복원 데이터 LIF IP 주소로의 라우팅을 허용해야 합니다.
* IRE 라우팅 테이블에는 IRE 에이전트가 작동할 수 있도록 공용 인터넷에 대한 경로도 허용되어야 합니다.


.가상 프라이빗 클라우드(VPC)
* IRE의 경우 운영 환경의 IP 주소 범위 내에서 VPC를 프로비저닝합니다. IP 주소는 기존 IP 주소와 충돌하지 않아야 합니다.
+
** VPC는 최소 64개의 IP 주소(/26 넷마스크) 용량을 확보해야 합니다.
** VPC는 공용 인터넷 액세스를 허용해야 합니다. 그렇지 않으면 Console 에이전트가 작동하지 않습니다.




.클라우드 권한
* Ransomware Resilience에는 AWS 환경에서 클린 복원을 수행하기 위해 올바른 IAM 권한이 있는 AWS 액세스 키와 시크릿이 필요합니다. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html["AWS에서 IAM 정책을 생성합니다"^] 다음 권한을 사용하여 새로 생성한 사용자에게 정책을 연결하십시오. 사용자를 생성한 후 IAM 자격 증명을 생성하여 클린 복원에 제공하십시오.


[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EC2Isolated recovery environmentFullAccess",
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:ResourceTag/rps::Isolated recovery environment-name": "*"
                }
            }
        },
        {
            "Sid": "EC2CreateAccess",
            "Effect": "Allow",
            "Action": [
                "ec2:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "EC2ReadPermissions",
            "Effect": "Allow",
            "Action": [
                "ec2:Describe*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "IAMFullAccess",
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:ResourceTag/rps::Isolated recovery environment-name": "*"
                }
            }
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucketCreation",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucketObjects",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*-netapp-Isolated recovery environment-state-bucket/*"
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucket",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*-netapp-Isolated recovery environment-state-bucket"
        }
    ]
}
----